<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sodanodo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.sodanodo':
      return '<p>' . t('Fetches and displays publications from a Zenodo community as an HTML list.') . '</p>';
  }
}

/**
 * Implements hook_cron().
 */
function sodanodo_cron() {
  \Drupal::service('sodanodo')->fetchAndStorePublications();
}
